{
  "formatVersion": "1.1",
  "component": {
    "group": "com.juliewoolie",
    "module": "delphi",
    "version": "0.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "delphi-0.5.0-SNAPSHOT.jar",
          "url": "delphi-0.5.0-SNAPSHOT.jar",
          "size": 88125,
          "sha512": "83ca294e70da92f386ec2a7a32442b6014625ea7cece4c1cdff63ecf4e413d1dbaca80d0b834d5dfc220b577d406ce5e11747cf0eb0f6583f2407411d0cccef4",
          "sha256": "46ac49ff5b8276ff95ab993b4e55b1e4f88ff84618c4953e02a3987229a9bc6d",
          "sha1": "a22dcd9651bc1c0ea5afa1372ce56c4124d01819",
          "md5": "8b8eb2d1b8b9ba5747599c574f13617a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "delphi-0.5.0-SNAPSHOT.jar",
          "url": "delphi-0.5.0-SNAPSHOT.jar",
          "size": 88125,
          "sha512": "83ca294e70da92f386ec2a7a32442b6014625ea7cece4c1cdff63ecf4e413d1dbaca80d0b834d5dfc220b577d406ce5e11747cf0eb0f6583f2407411d0cccef4",
          "sha256": "46ac49ff5b8276ff95ab993b4e55b1e4f88ff84618c4953e02a3987229a9bc6d",
          "sha1": "a22dcd9651bc1c0ea5afa1372ce56c4124d01819",
          "md5": "8b8eb2d1b8b9ba5747599c574f13617a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "delphi-0.5.0-SNAPSHOT-sources.jar",
          "url": "delphi-0.5.0-SNAPSHOT-sources.jar",
          "size": 85470,
          "sha512": "212f735fecf1bc65570ef9f5fed9676046582ee51325b15f98f14d2a49109466c846869221f2c53ebbfc8d7feef1b70db98616b72c0347c8d0f24fe8b2ef8ad2",
          "sha256": "510558e56c17e51c1a74049939a033d4f1e2a5ad5995ff2478a41f14952609a6",
          "sha1": "1e6e3e587678ec1cee4cd45ea47e622596b0a980",
          "md5": "c392091b2ce642175fe50aa9a09593f7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "delphi-0.5.0-SNAPSHOT-javadoc.jar",
          "url": "delphi-0.5.0-SNAPSHOT-javadoc.jar",
          "size": 4551518,
          "sha512": "148e8fed25fb0327be5aae3fd005253b558b7f2104a5a3deb40c85739f186d6d641593840c55be321751b3fcfccf28143712e76c4db8dae2859818240b99d96d",
          "sha256": "28fc6b693962dca3078484de13795acf791b08ceae8b0e7ef4a7fabf8b9a1320",
          "sha1": "e530301a6899ab219836bb097bcd5183f428c084",
          "md5": "857034c08e71d90cb54ea775a1274625"
        }
      ]
    }
  ]
}
